language: python
python:
  - "3.5"

notifications:
  email:
    - pblouw@gmail.com

# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
script:
  - python -m nltk.downloader punkt
  - python -m spacy.en.download
  - flake8 pysem
  - py.test