language: python
python:
  - "3.5"

notifications:
  email:
    - pblouw@gmail.com

# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
script:
  - python -m nltk.downloader punkt
  - python -m nltk.downloader stopwords
  - python -m spacy.en.download
  - python setup.py install
  - flake8 pysem
  - py.test --cov=./

after_success:
  - bash <(curl -s https://codecov.io/bash) -t fa1c3214-e108-4cac-91ff-37fb20ee3b7e